### ISSUE TITLE
Various improvements

### ISSUE THREAD

**Issue by PauFCB** [rasmuslos/AmpFin#13]
Hi, despite I'm currently using the version 1.0, I have some suggestions to improve the app:
- [ ] When you are somewhere in the app but want to go to the main screen, wold be nice to do that with one click on the library icon at the bottom (currently only working if you are in the downloads or the search sections, but not when you are in the album view). 
- [ ] Improve the animation to go back swiping right anywhere on the screen, bc if you do that now in the track list don't work properly and sometimes I add items to the queue when I don't want to.
- [ ] Sometimes (specially with lighter colors) the play controls looks very hidden.
- [x] First, a long press in a single song to open up a menu for download, add playlist etc
- [x] Improve the animation when you swip down in the now playing screen. It would be nice if the floating window could be moved up or down holding before disappear.
- [x] When playing a song and looking the track list, put a movement icon to know which song is currently playing (or shadow the whole song line).
- [x] I'm not able to order albums by date added (new ones to old).
- [x] Hide the volume popup everytime I change the volume with the slider.

That's all, I'm enjoying the app, and thanks again for your amazing work!

**Comment by rasmuslos** [comment]
Hey, thanks for your feedback!

- The context menu for tracks is already implemented (and even drag and drop)
- The now playing view is presented in a sheet and the missing animation is something I hate quite a lot. There is no good way to presented sheet (something with an animation) so that it covers the whole screen. You can only use `fullscreenCover` for that, but it has no animations. I think there is a way to do it using UIKit, but I have refused to do this (until now probably) mostly out of principle

The other suggestions are quite good, I will look into them, but I am not sure if thinks like the volume control are actually possible

**Comment by PauFCB** [comment]
Can this type of a floating window in the now playing screen be a solution for the good animation? (From the app called Fintunes).
![IMG_2603](https://github.com/rasmuslos/AmpFin/assets/55207285/7b17ed8d-62b7-45fc-83db-ff6b1e9973f5)

**Comment by rasmuslos** [comment]
Yes, this is possible and I have used it for ShelfPlayer version one but ended up disliking it so much that I changed it to `fullscreenCover`

**Comment by rasmuslos** [comment]
I will close this issue for now, the image colors should be fine and I cannot really do anything about the swiping or going back to to first view when pressing the tabbar icon, because SwiftUI does not have any APIs for doing either. If we are lucky we might get something at WWDC24 but I personally would not get my hopes up
