### ISSUE TITLE
iPadOS App

### ISSUE THREAD

**Issue by pavelzw** [rasmuslos/AmpFin#21]
Love the app! Is an iPad version planned as well? (same question for ShelfPlayer)

**Comment by rasmuslos** [comment]
I definitely want to expand to other platforms, but not before iOS 18. I really hope that SwiftUI gets better until then so that you don't have to rely on UIKit on other devices.

But iPads are at the very end of the list of devices I want to expand to, mostly because I have never understood and therefore never used them...
