### ISSUE TITLE
Lyrics tab always loading

### ISSUE THREAD

**Issue by szaszlyki21** [rasmuslos/AmpFin#4]
Hi,
Yesterday I installed Ampfin on my phone and it looks amazing! Just the lyrics tab in the player doesnt load... I couldnt find how it works - Does it scrape some kind of lyric database website or does it check if there are local lrc files in the directory of the album? I'm new to Jellyfin so maybe a skipped an important part of making lyrics work

**Comment by rasmuslos** [comment]
Hey,
glad that you enjoy the app!
Theoretically, there should have been a warning when you open the player, the Jellyfin server only supports lyrics on version 10.9 and onwards, so only when you are running the unstable (development) version. I will probably remove the lyrics tab temporally in the next release, because most other clients are incompatible and using it is not a great experience.
